SHEET_SCHEMAS: dict[str, list[str]] = {
    "Rooms": [
        "room_id",
        "floor",
        "room_type",
        "zone",
        "capacity",
        "noise_level",
        "status",
        "assigned_guest",
        "last_cleaned",
        "maintenance_status",
    ],
    "Guests": [
        "guest_id",
        "name",
        "age",
        "guest_type",
        "stay_purpose",
        "group_size",
        "loyalty_status",
        "visit_count",
    ],
    "Bookings": [
        "booking_id",
        "guest_id",
        "room_id",
        "checkin_date",
        "checkout_date",
        "booking_created_time",
        "booking_source",
        "status",
    ],
    "Payments": [
        "payment_id",
        "booking_id",
        "guest_id",
        "amount",
        "payment_status",
        "transaction_id",
    ],
    "Services": [
        "service_id",
        "service_name",
        "description",
        "price",
        "active",
    ],
    "Complaints": [
        "complaint_id",
        "guest_id",
        "booking_id",
        "issue",
        "resolution",
        "status",
    ],
}

PRIMARY_KEYS: dict[str, str] = {
    "Rooms": "room_id",
    "Guests": "guest_id",
    "Bookings": "booking_id",
    "Payments": "payment_id",
    "Services": "service_id",
    "Complaints": "complaint_id",
}
